### PR TITLE
Support for js platform

### PR DESCRIPTION
**Pull request by jeancharles-roger**
Hi, I wanted to test Oolong on JavaScript. 

I added the target and to implement `runBlocking` for the tests I removed the returned type. I also added `@JsName()' for test methods, the js platform doesn't support spaces in method names.

I don't know if it is the good way to do it but I was able to play with Oolong :).

I'm using [Bulma](https://bulma.io) and [bulma-kotlin](https://github.com/centyllion/bulma-kotlin):
Capture d’écran 2020-06-01 à 08 02 41

### CODE REVIEW

**Comment by jeancharles-roger** [comment]
I played with the [ToDo](https://centyllion.com/assets/demo/oolong/) :)

Capture d’écran 2020-06-01 à 13 58 49

**Comment by pardom** [comment]
Hi @jeancharles-roger, thanks for the PR! We actually had JS support implemented, but decided to remove support for a few reasons:
* Established projects like Elm and [Raj](https://github.com/andrejewski/raj)
* Kotlin2JS peculiarities that add complexity
* Poor adoption for JS target

There is actually a JS implementation of all the samples and a TodoMVC implementation if you look through the [revision history](https://github.com/oolong-kt/oolong/commit/db7644cdb026bd7d6b72b1dab9cce9563aa4a302).

However, I'm happy to start a discussion here to revisit.

@oolong-kt/developers

**Comment by pardom** [comment]
Here's the TodoMVC implementation https://github.com/oolong-kt/oolong/tree/45817bf3611befbdcb3caf32d617794c572711e2/samples/todomvc

**Comment by jeancharles-roger** [comment]
Hi, 

Thanks for the precisions. I was surprised that there was no JS support, I now understand.

JS target can be temperamental 😁. I've been using it for more than two years and I've seen quite some changes and upgrades. For instance, the compilation time is now much better, I'm waiting to see the 1.4 for more improvements. 

I have several projects using Kotlin they don't use all the targets, it's a mix. It includes:
- native for desktops (linux, windows and macOS) and iOS,
- jvm for server and android,
- js for browser.

I did only played with Oolong yet, I haven't done much yet. It comes a long way to help with model immutability. I'm really interested it's capability to build a common model and control with no regard to the target interface. I'd like to test it for a web app with iOS and Android companions and for a desktop application with a UI, CLI and scripting API. 

The argument I could give to support the JS platform it's the universality of the approach. In my case, it would be a real problem not to have since I try to build a common ground between my projects (I mean a common approach, not necessarily code sharing).

I understand that it's a lot of work to support all targets. Moreover, I'm justing testing out since last week. I don't know yet if I'll use it in the long run (I really like it so far 😁). 

This is a long response to basically say that I don't have real arguments other than the universality that comes with a cost. 

I will continue to test it and I'll report later if I'm actually using it.

King regards.
Jean-Charles

**Comment by jeancharles-roger** [comment]
After a few months, I didn't had the opportunity to use oolong. I close the PR.

Thanks for consideration.

**Pull request closed without merging**
