### PR TITLE
Updating kotlin and other dependencies

### PR DESCRIPTION
**Pull request by dallasgutauckis**

### CODE REVIEW

**Comment by dallasgutauckis** [comment]
I didn't test this -- just made the change on the plane and had an issue w/ xcrun failing, so was hoping to see the result from a workflow run.

**Comment by dallasgutauckis** [comment]
@pardom needs another approval after I fixed the test that was failing to compile due to changes

**Review by pardom — APPROVED** [review]
Nice!

**Comment by dallasgutauckis** [comment]
I don't see a merge button on my end; you may have to do that @pardom

**Pull request merged**
